// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Models;

#nullable disable

namespace ParksApi.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    [Migration("20230401170655_AddUsersToDb")]
    partial class AddUsersToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("NationalPark")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<bool>("StatePark")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            City = "Grand Canyon Village",
                            Name = "Grand Canyon National Park",
                            NationalPark = true,
                            State = "Arizona",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 2,
                            City = "Aurora",
                            Name = "Cherry Creek State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 3,
                            City = "Littleton",
                            Name = "Chatfield State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 4,
                            City = "Yosemite National Park",
                            Name = "Yosemite National Park",
                            NationalPark = true,
                            State = "California",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 5,
                            City = "West Glacier",
                            Name = "Glacier National Park",
                            NationalPark = true,
                            State = "Montana",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 6,
                            City = "Commerce City",
                            Name = "Barr Lake State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 7,
                            City = "Colorado Springs",
                            Name = "Cheyenne Mountain State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 8,
                            City = "Crawford",
                            Name = "Crawford State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 9,
                            City = "Lake George",
                            Name = "Eleven Mile State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 10,
                            City = "Orchard",
                            Name = "Jackson Lake State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 11,
                            City = "Hasty",
                            Name = "John Martin Reservoir State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 12,
                            City = "Pueblo",
                            Name = "Lake Pueblo State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 13,
                            City = "Mancos",
                            Name = "Mancos State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 14,
                            City = "Ridgway",
                            Name = "Ridgway State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 15,
                            City = "Firestone",
                            Name = "St. Vrain State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 16,
                            City = "Pine",
                            Name = "Staunton State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 17,
                            City = "Clark",
                            Name = "Steamboat Lake State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 18,
                            City = "Trinidad",
                            Name = "Trinidad Lake State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 19,
                            City = "Denali Park",
                            Name = "Denali National Park",
                            NationalPark = true,
                            State = "Alaska",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 20,
                            City = "Fairbanks",
                            Name = "Gates of the Arctic National Park",
                            NationalPark = true,
                            State = "Alaska",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 21,
                            City = "Gustavus",
                            Name = "Glacier Bay National Park Preserve",
                            NationalPark = true,
                            State = "Alaska",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 22,
                            City = "King Salmon",
                            Name = "Katmai National Park",
                            NationalPark = true,
                            State = "Alaska",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 23,
                            City = "Seward",
                            Name = "Kenai Fjords National Park",
                            NationalPark = true,
                            State = "Alaska",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 24,
                            City = "Kotzebue",
                            Name = "Kobuk Valley National Park",
                            NationalPark = true,
                            State = "Alaska",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 25,
                            City = "Anchorage",
                            Name = "Lake Clark National Park and Preserve",
                            NationalPark = true,
                            State = "Alaska",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 26,
                            City = "Copper Center",
                            Name = "Wrangell-St. Elias National Park and Preserve",
                            NationalPark = true,
                            State = "Alaska",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 27,
                            City = "Petrified Forest",
                            Name = "Petrified Forest National Park",
                            NationalPark = true,
                            State = "Arizona",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 28,
                            City = "Tucson",
                            Name = "Saguaro National Park",
                            NationalPark = true,
                            State = "Arizona",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 29,
                            City = "Hot Springs",
                            Name = "Hot Springs National Park",
                            NationalPark = true,
                            State = "Arkansas",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 30,
                            City = "Ventura",
                            Name = "Channel Islands National Park",
                            NationalPark = true,
                            State = "California",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 31,
                            City = "Furnace Creek",
                            Name = "Death Valley National Park",
                            NationalPark = true,
                            State = "California",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 32,
                            City = "Joshua Tree",
                            Name = "Joshua Tree National Park",
                            NationalPark = true,
                            State = "California",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 33,
                            City = "Three Rivers",
                            Name = "Kings Canyon National Park",
                            NationalPark = true,
                            State = "California",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 34,
                            City = "Mineral",
                            Name = "Lassen Volcanic National Park",
                            NationalPark = true,
                            State = "California",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 35,
                            City = "Paicines",
                            Name = "Pinnacles National Park",
                            NationalPark = true,
                            State = "California",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 36,
                            City = "Crescent City",
                            Name = "Del Norte Coast Redwoods State Park",
                            NationalPark = false,
                            State = "California",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 37,
                            City = "Three Rivers",
                            Name = "Sequoia National Park",
                            NationalPark = true,
                            State = "California",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 38,
                            City = "Montrose",
                            Name = "Black Canyon of the Gunnison National Park",
                            NationalPark = true,
                            State = "Colorado",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 39,
                            City = "Mosca",
                            Name = "Great Sand Dunes National Park",
                            NationalPark = true,
                            State = "Colorado",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 40,
                            City = "Mesa Verde National Park",
                            Name = "Mesa Verde National Park",
                            NationalPark = true,
                            State = "Colorado",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 41,
                            City = "Homestead",
                            Name = "Biscayne National Park",
                            NationalPark = true,
                            State = "Florida",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 42,
                            City = "Homestead",
                            Name = "Dry Tortugas National Park",
                            NationalPark = true,
                            State = "Florida",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 43,
                            City = "Homestead",
                            Name = "Everglades National Park",
                            NationalPark = true,
                            State = "Florida",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 44,
                            City = "Makawao",
                            Name = "Haleakala National Park",
                            NationalPark = true,
                            State = "Hawaii",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 45,
                            City = "Hawaii National Park",
                            Name = "Hawaii Volcanoes National Park",
                            NationalPark = true,
                            State = "Hawaii",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 46,
                            City = "Yellowstone National Park",
                            Name = "Yellowstone National Park",
                            NationalPark = true,
                            State = "Wyoming",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 47,
                            City = "Porter",
                            Name = "Indiana Dunes National Park",
                            NationalPark = true,
                            State = "Indiana",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 48,
                            City = "Bar Harbor",
                            Name = "Acadia National Park",
                            NationalPark = true,
                            State = "Maine",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 49,
                            City = "Houghton",
                            Name = "Isle Royale National Park",
                            NationalPark = true,
                            State = "Michigan",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 50,
                            City = "International Falls",
                            Name = "Voyageurs National Park",
                            NationalPark = true,
                            State = "Minnesota",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 51,
                            City = "St. Louis",
                            Name = "Gateway Arch National Park",
                            NationalPark = true,
                            State = "Missouri",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 52,
                            City = "Peninsula",
                            Name = "Cuyahoga Valley National Park",
                            NationalPark = true,
                            State = "Ohio",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 53,
                            City = "Baker",
                            Name = "Great Basin National Park",
                            NationalPark = true,
                            State = "Nevada",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 54,
                            City = "Carlsbad",
                            Name = "Carlsbad Caverns National Park",
                            NationalPark = true,
                            State = "New Mexico",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 55,
                            City = "Alamogordo",
                            Name = "White Sands National Park",
                            NationalPark = true,
                            State = "New Mexico",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 56,
                            City = "Medora",
                            Name = "Theodore Roosevelt National Park",
                            NationalPark = true,
                            State = "North Dakota",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 57,
                            City = "Gatlinburg",
                            Name = "Great Smoky Mountains",
                            NationalPark = true,
                            State = "Tenneessee",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 58,
                            City = "Crater Lake",
                            Name = "Crater Lake National Park",
                            NationalPark = true,
                            State = "Oregon",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 59,
                            City = "Hopkins",
                            Name = "Congaree National Park",
                            NationalPark = true,
                            State = "South Carolina",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 60,
                            City = "Interior",
                            Name = "Badlands National Park",
                            NationalPark = true,
                            State = "South Dakota",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 61,
                            City = "Hot Springs",
                            Name = "Wind Cave National Park",
                            NationalPark = true,
                            State = "South Dakota",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 62,
                            City = "",
                            Name = "Arches National Park",
                            NationalPark = true,
                            State = "Utah",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 63,
                            City = "Crescent City",
                            Name = "Redwood National Park",
                            NationalPark = true,
                            State = "California",
                            StatePark = false
                        });
                });

            modelBuilder.Entity("ParksApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
