// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Models;

#nullable disable

namespace ParksApi.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    [Migration("20230331180757_UpdateStateRequiredRange")]
    partial class UpdateStateRequiredRange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("NationalPark")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("StatePark")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            City = "Grand Canyon Village",
                            Name = "Grand Canyon National Park",
                            NationalPark = true,
                            State = "Arizona",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 2,
                            City = "Aurora",
                            Name = "Cherry Creek State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 3,
                            City = "Littleton",
                            Name = "Chatfield State Park",
                            NationalPark = false,
                            State = "Colorado",
                            StatePark = true
                        },
                        new
                        {
                            ParkId = 4,
                            City = "Yosemite National Park",
                            Name = "Yosemite National Park",
                            NationalPark = true,
                            State = "California",
                            StatePark = false
                        },
                        new
                        {
                            ParkId = 5,
                            City = "West Glacier",
                            Name = "Glacier National Park",
                            NationalPark = true,
                            State = "Montana",
                            StatePark = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
